# Generated by Django 4.1.3 on 2023-07-12 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_customer_address'),
        ('Franchise', '0002_center_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Diam dolor diam ipsum sit amet diam et eos erat ipsum', max_length=400)),
                ('purchase_price', models.IntegerField(default=300)),
                ('hsn_number', models.CharField(default='Abc', max_length=20)),
                ('price', models.IntegerField(default=500)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('tax', models.FloatField(default=5)),
                ('stock', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Franchise.center')),
            ],
        ),
        migrations.CreateModel(
            name='CenterServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Diam dolor diam ipsum sit amet diam et eos erat ipsum', max_length=400)),
                ('price', models.IntegerField(default=500)),
                ('tax', models.FloatField(default=5)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Franchise.center')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehical_km', models.IntegerField(default=0)),
                ('progress', models.CharField(choices=[('WAITING', 'Waiting'), ('DOING', 'Doing')], default='WAITING', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_services_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('final_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Franchise.center')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
                ('services', models.ManyToManyField(blank=True, null=True, to='ERP.centerservices')),
            ],
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_image', models.ImageField(blank=True, null=True, upload_to='media/updateimg')),
                ('update_title', models.CharField(blank=True, max_length=50, null=True)),
                ('update_description', models.CharField(blank=True, max_length=200, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('NA', 'NA'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('DONE', 'DONE'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='NA', max_length=50)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Franchise.center')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employee')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vehical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.vehical'),
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('slip', models.FileField(upload_to='media/payslips')),
                ('txnid', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('report', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.centerproduct')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
            ],
            options={
                'unique_together': {('service', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT MARKED', 'NOT MARKED'), ('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], default='NOT MARKED', max_length=50)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
