# Generated by Django 4.1.3 on 2023-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.AddField(
            model_name='service',
            name='time_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
