# Generated by Django 4.1.3 on 2023-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_remove_service_customer_service_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehical',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehical',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
