# Generated by Django 4.1.3 on 2023-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slider_img1', models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg')),
                ('slider_img2', models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg')),
                ('what', models.CharField(blank=True, max_length=50, null=True)),
                ('what_img', models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg')),
                ('how', models.CharField(blank=True, max_length=50, null=True)),
                ('how_img', models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg')),
                ('when', models.CharField(blank=True, max_length=50, null=True)),
                ('when_img', models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg')),
            ],
        ),
    ]
