# Generated by Django 4.1.3 on 2023-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_servicedisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedisplay',
            name='how',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='servicedisplay',
            name='what',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='servicedisplay',
            name='when',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
