# Generated by Django 4.1.3 on 2023-07-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_servicedisplay_how_alter_servicedisplay_what_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedisplay',
            name='why',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='servicedisplay',
            name='why_img',
            field=models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg'),
        ),
    ]
